name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build APK

    runs-on: ubuntu-latest

    steps:
    
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    # Step 2: Set up JDK 17
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
        
    # Step 3: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
            
    # Step 4: Grant execute permission for Gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 5: Create a Keystore File
    - name: Create Keystore File
      run: |
        mkdir -p app
        echo "$NOTIFY_ME_KEYSTORE_BASE64" | tr -d '\n' | base64 -d > ${{ github.workspace }}/app/keystore.jks
      env:
        NOTIFY_ME_KEYSTORE_BASE64: ${{ secrets.NOTIFY_ME_KEYSTORE_BASE64 }}
        

    # Step 6: Build the APK
    - name: Build APK
      run: ./gradlew assembleRelease -PkeystorePath=${{ github.workspace }}/app/keystore.jks
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.12-7/x64
        NOTIFY_ME_KEYSTORE_PATH: ${{ github.workspace }}/app/keystore.jks
        NOTIFY_ME_KEY_ALIAS: ${{ secrets.NOTIFY_ME_KEY_ALIAS }}
        NOTIFY_ME_KEY_PASSWORD: ${{ secrets.NOTIFY_ME_KEY_PASSWORD }}
        NOTIFY_ME_KEYSTORE_PASSWORD: ${{ secrets.NOTIFY_ME_KEYSTORE_PASSWORD }}

    # Step 7: Find the generated APK and rename it with the tag name
    - name: Find and Rename APK
      run: |
        APK_PATH=$(find app/build/outputs/apk/ -name "*.apk" | head -n 1)
        if [ -z "$APK_PATH" ]; then
          echo "APK not found"
          exit 1
        fi
        mv "$APK_PATH" "app/build/outputs/apk/release/notify-me-${GITHUB_REF_NAME}.apk"
